version: "3.3"

services:
    sparqlanything:
        container_name: sparqlanything
        image: sparqlanything
        build:
            context: .
            dockerfile: .docker/Dockerfile.sparqlanything
        restart: always
        ports:
            - "3000:3000"
    serveontologies:
        container_name: serveontologies
        image: serveontologies
        build:
            context: .
            dockerfile: .docker/Dockerfile.serveontologies
        restart: always
        ports:
            - "8080:8080"
    webvowl:
        container_name: webvowl
        image: webvowl
        build:
            context: .
            dockerfile: .docker/Dockerfile.webvowl
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - serveontologies
