version: "3.3"

services:
    serveontologies:
        container_name: serveontologies
        image: nginx
        restart: always
        networks:
            - network
        volumes:
            - .docker/nginx.serveontologies.conf:/etc/nginx/nginx.conf
            - ./ontology/kejazz/kejazz.owl:/kejazz.owl
            - ./ontology/chord-annotations/chord-annotations.owl:/chord-annotations.owl
            - ./ontology/chord-annotations/mto.owl:/mto.owl

    webvowl:
        container_name: webvowl
        image: webvowl
        build:
            context: .
            dockerfile: .docker/Dockerfile.webvowl
        restart: always
        networks:
            - network
        depends_on:
            - serveontologies
    
    lode:
        container_name: lode
        image: lode
        build:
            context: .
            dockerfile: .docker/Dockerfile.lode
            args:
                LODE_EXTERNAL_URL: "http://localhost:8080/lode/"
                WEBVOWL_EXTERNAL_URL: "http://localhost:8080/webvowl#iri="
        restart: always
        networks:
            - network
        depends_on:
            - webvowl

    sparqlanything:
        container_name: sparqlanything
        image: sparqlanything
        build:
            context: .
            dockerfile: .docker/Dockerfile.sparqlanything
        restart: always
        networks:
            - network

    lodview:
        container_name: lodview
        image: lodview
        build:
            context: .
            dockerfile: .docker/Dockerfile.lodview
        restart: always
        volumes:
            - .docker/conf.lodview.ttl:/LodView/src/main/webapp/WEB-INF/conf.ttl
        networks:
            - network

    fuseki:
        container_name: fuseki
        image: fuseki
        build:
            context: .
            dockerfile: .docker/Dockerfile.fuseki
        restart: always
        networks:
            - network

    app:
        container_name: app
        image: app
        build:
            context: .
            dockerfile: .docker/Dockerfile.app
        restart: always
        networks:
            - network

    proxy:
        container_name: proxy
        image: nginx
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - serveontologies
            - lode
            - webvowl
            - sparqlanything
            - fuseki
            - app
        networks:
            - network
        volumes:
            - .docker/nginx.proxy.conf:/etc/nginx/nginx.conf
            - .docker/index.html:/index.html

networks:
  network:
