FROM  maven:3.6.3-jdk-8

RUN git clone https://github.com/essepuntato/LODE.git
WORKDIR /LODE

ARG LODE_EXTERNAL_URL
ARG WEBVOWL_EXTERNAL_URL
RUN echo "externalURL=${LODE_EXTERNAL_URL}\nwebvowl=${WEBVOWL_EXTERNAL_URL}\nuseHTTPs=false" > src/main/webapp/config.properties

COPY .docker/LodeServlet.java src/main/java/it/essepuntato/lode/LodeServlet.java
COPY .docker/GetSource.java src/main/java/it/essepuntato/lode/GetSource.java

EXPOSE 8080
CMD ["mvn", "jetty:run"]